---
# tasks file for configure_vpn
---
- name: Create VirtualHubs
  uri:
    url: "{{ vpn_server_api_url }}/hub/create"
    method: POST
    body_format: json
    body: '{"HubName": "{{ item }}"}'
    status_code: 200
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  loop: "{{ vpn_virtual_hubs}}"
  register: virtual_hub_creation_result

- name: Create Users in VirtualHubs
  uri:
    url: "{{ vpn_server_api_url }}/user/create"
    method: POST
    body_format: json
    body: '{"HubName": "{{ item.hub }}", "AuthType": "Password", "Name": "{{ item.username }}", "AuthPassword": "{{ item.password }}"}'
    status_code: 200
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  loop: "{{ vpn_users}}"
  register: user_creation_result

- name: Disable Anonymous Enumeration for VirtualHubs
  uri:
    url: "{{ vpn_server_api_url }}/hub/configure"
    method: POST
    body_format: json
    body: '{"HubName": "{{ item }}", "NoEnum": true}'
    status_code: 200
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  loop: "{{ vpn_virtual_hubs}}"